services:
  redis:
    image: redis/redis-stack:latest
    volumes:
      - redis-data:/data
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001  # RedisInsight port

volumes:
  redis-data: