general:
  use_uvloop: true
  front_end:
    _type: fastapi
    cors:
      allow_origins: ['*']
      allow_methods:
        - GET
        - POST
        - OPTIONS
    endpoints:
      - path: /case/{case_id}
        method: GET
        description: Gets the mediation case for the given case ID.
        function_name: get_mediation_case
      - path: /case/{case_id}/session/{session_id}
        method: GET
        description: Gets the mediation session data for the given case ID and session ID.
        function_name: get_mediation_session
      - path: /case/{case_id}/session/{session_id}/send
        method: POST
        description: Sends a message to the mediation session for the given case ID and session ID.
        function_name: send_message_to_mediation_session
  telemetry:
    enabled: false
    tracing:
      phoenix:
        _type: phoenix
        endpoint: http://localhost:6006/v1/traces
        project: default

retrievers:
  milvus_retriever:
    _type: milvus_retriever
    uri: "http://localhost:19530"
    embedding_model: "nv-embedqa-e5-v5"
    collection_name: "aiq_case_documents"
    vector_field: "embedding"
    search_params:
      metric_type: "IP" # works best with nv-embedqa-e5-v5

llms:
  nim_llm:
    _type: nim
    base_url: http://192.168.5.96:1234/v1
    model_name: qwen3-8b
    max_tokens: 10000
    temperature: 0.7
  mediation_llm:
    _type: nim
    base_url: http://192.168.5.96:1234/v1
    model_name: qwen3-8b
    max_tokens: 10000
    temperature: 0.7

memory:
  redis_memory:
    _type: redis_memory
    connection_url: redis://localhost:6379/0

functions:
  case_document_rag:
    _type: case_document_rag
    retriever: milvus_retriever
    llm_name: nim_llm
    collection_name: "mediation_simulator_case_documents"
    top_k: 5
  case_query_agent:
    _type: case_query_agent
    llm_name: nim_llm
    tool_names:
      - case_document_rag
    verbose: true
    max_iterations: 5

  # server route functions
  get_mediation_case:
    _type: server/get_mediation_case
  get_mediation_session:
    _type: server/get_mediation_session
  send_message_to_mediation_session:
    _type: mediation

embedders:
  nv-embedqa-e5-v5:
    _type: nim
    base_url: http://192.168.5.96:8000/v1
    model_name: nvidia/nv-embedqa-e5-v5

workflow:
  _type: mediation
  llm: mediation_llm
  data_dir: ./data
